total_games: 5000
games_per_train: 25
iters_per_train: 10
ckpt_frequency: 2
batch_size: 1024
seed: 0
lr: 1.0e-3
self_play_args:
  sim_num: 500
  explore_factor: 3.5
  temperature: 1.0
  # Dirichlet noise Dir(alpha)
  alpha: 0.5
  # p(s,a) = (1-eps)p(s,a) + eps*noise
  epsilon: 0.25